from selenium.webdriver.chrome.options import Options
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestadminloginerror():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testadminloginerror(self):
    self.driver.get("http://127.0.0.1:5500/teton/1.6/")
    self.driver.set_window_size(1270, 990)
    self.driver.find_element(By.LINK_TEXT, "Admin").click()
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys(" vggg")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("gggg")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, "form > div").click()
    self.driver.find_element(By.CSS_SELECTOR, "form > div").click()
    self.driver.find_element(By.CSS_SELECTOR, "form > div").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "form > div")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."
  
