from selenium.webdriver.chrome.options import Options
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestadminhomedisplayed():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testadminhomedisplayed(self):
    self.driver.get("http://127.0.0.1:58211/teton/1.6/")
    self.driver.set_window_size(1270, 992)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-title > h1")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".header-top").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-top").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".header-top")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-title > h2")
    assert len(elements) > 0
  
